//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vasut_adatbazis
{
    using System;
    using System.Collections.Generic;
    
    public partial class enMenetrend
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enMenetrend()
        {
            this.enVonat = new HashSet<enVonat>();
            this.enMegallo = new HashSet<enMegallo>();
        }
    
        public int Id { get; set; }
        public System.DateTime Indulas_ido { get; set; }
        public System.DateTime Erkezes_ido { get; set; }
        public string Honnan { get; set; }
        public string Hova { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enVonat> enVonat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enMegallo> enMegallo { get; set; }
    }
}
