//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vasut_adatbazis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cnVasut : DbContext
    {
        public cnVasut()
            : base("name=cnVasut")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<enVonat> enVonatok { get; set; }
        public virtual DbSet<enMenetrend> enMenetrendek { get; set; }
        public virtual DbSet<enMegallo> enMegallok { get; set; }
    }
}
