//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vasut_adatbazis
{
    using System;
    using System.Collections.Generic;
    
    public partial class enVonat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enVonat()
        {
            this.enMenetrend = new HashSet<enMenetrend>();
        }
    
        public int Id { get; set; }
        public string Nev { get; set; }
        public System.DateTime Gyartas { get; set; }
        public int Vagonszam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enMenetrend> enMenetrend { get; set; }
    }
}
